apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flak-deploy
  labels:
    app: {{ .Values.flaskapp | default "flaskapp" }}
spec:
  replicas: {{ .Values.flaskapp | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.flaskapp | default "flaskapp" }}
  template:
    metadata:
      labels:
        app: {{ .Values.flaskapp | default "flaskapp" }}
    spec:
      containers:
        - image: {{ .Values.flaskapp | default "ababa777/flaskapp:latest" }}
          name: {{ .Values.flaskapp | default "flaskapp" }}
          command: ["python3"]
          args: ["app.py", "runserver", "--host", "0.0.0.0", "-d", "-r"]
          ports:
            - containerPort: {{ .Values.flaskapp | default 5000 }}
          envFrom:
          - secretRef:
            name: {{ .Values.secrets }}
