apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.flaskservice.name | default "flask" }}
spec:
  ports:
  - port: {{ .Values.flaskservice | default 5000 }}
    protocol: TCP
    targetPort: {{ .Values.flaskservice | default 5000 }}
  selector:
    app: {{ .Values.flaskservice | default "flaskapp" }}
  type: {{ .Values.flaskservice | default "LoadBalancer" }}