apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlservice.name | default "mysql" }}  
  labels:
    app: {{ .Values.mysqlservice.label | default "mysql" }}  
spec:
  ports:
  - port: {{ .Values.mysqlservice.port | default 3306 }}
    protocol: TCP
    name: {{ .Values.mysqlservice.portname | default "mysql" }}  
  selector:
    app: {{ .Values.mysqlservice.selector | default "mysql" }}  
  type: {{ .Values.mysqlservice.type | default "LoadBalancer" }} 