apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql-deploy
  labels:
    app: {{ .Values.mysql | default "mysql" }}
spec:
  replicas: {{ .Values.mysql | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.mysql | default "mysql" }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql | default "mysql" }}
    spec:
      containers:
      - image: {{ .Values.mysql | default "jamielsharief/mysql:latest" }} 
        name: {{ .Values.mysql | default "mysql" }}      
        ports:
        - containerPort: {{ .Values.mysql | default 3306 }}
        envFrom:
        - secretRef:
          name: {{ .Values.secret }}
        volumeMounts:
            - name: {{ .Values.pv | default "mysql-persistent-storage" }}
              mountPath: {{ .Values.mysql | default "/var/lib/mysql" }} 
      
      volumes:
        - name: {{ .Values.pv | default "mysql-persistent-storage" }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc | default "mysql-pv-claim" }} 