apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql-deploy
  labels:
    app: {{ .Values.mysql.label | default "mysql" }}
spec:
  replicas: {{ .Values.mysql.repl | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.mysql.label | default "mysql" }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.label | default "mysql" }}
    spec:
      containers:
      - image: {{ .Values.mysql.image | default "jamielsharief/mysql:latest" }} 
        name: {{ .Values.mysql.name | default "mysql" }}      
        ports:
        - containerPort: {{ .Values.mysql.port | default 3306 }}
        envFrom:
        - secretRef:
          name: {{ .Values.secret.name }}
        volumeMounts:
            - name: {{ .Values.pv.name | default "mysql-persistent-storage" }}
              mountPath: {{ .Values.mysql.mountpath | default "/var/lib/mysql" }} 
      
      volumes:
        - name: {{ .Values.pv.name | default "mysql-persistent-storage" }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name | default "mysql-pv-claim" }} 