apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlservice | default "mysql" }}  
  labels:
    app: {{ .Values.mysqlservice | default "mysql" }}  
spec:
  ports:
  - port: {{ .Values.mysqlservice | default 3306 }}
    protocol: TCP
    name: {{ .Values.mysqlservice | default "mysql" }}  
  selector:
    app: {{ .Values.mysqlservice | default "mysql" }}  
  type: {{ .Values.mysqlservice | default "LoadBalancer" }} 