apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pv-claim
spec:
  storageClassName: {{ .Values.storageclass.name | default "manual" }}
  accessModes:
    - {{ .Values.pvc.accmode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage | default "2Gi" }} 