apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pv-claim
spec:
  storageClassName: {{ .Values.storageclass | default "manual" }}
  accessModes:
    - {{ .Values.pvc | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.pvc | default "2Gi" }} 