apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mysql-pv-volume
  labels:
    type: {{ .Values.pv | default "local" }}
spec:
  storageClassName: {{ .Values.storageclass | default "manual" }}
  capacity:
    storage: {{ .Values.pv | default "2Gi" }} 
  accessModes:
    - {{ .Values.pv | default "ReadWriteOnce" }}
  persistentVolumeReclaimPolicy: {{ .Values.pv | default "Retain" }} 
  hostPath:
    path: {{ .Values.pv | default "/mnt/data" }} 