apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mysql-pv-volume
  labels:
    type: {{ .Values.pv.label.type | default "local" }}
spec:
  storageClassName: {{ .Values.storageclass.name | default "manual" }}
  capacity:
    storage: {{ .Values.pv.storage | default "2Gi" }} 
  accessModes:
    - {{ .Values.pv.accmode | default "ReadWriteOnce" }}
  persistentVolumeReclaimPolicy: {{ .Values.pv.reclaimpolicy | default "Retain" }} 
  hostPath:
    path: {{ .Values.pv.path | default "/mnt/data" }} 