apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-flask-secrets
type: {{ .Values.secret.type | default "Opaque" }}
stringData:
{{- range $key, $value := .Value.secrets.data }}
  {{ $key }}: {{ $value | b64enc }}
{{ end }}