apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deploy
  labels:
    app: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - image: ababa777/flaskapp:latest
        name: flaskapp
        # imagePullPolicy: Never
        # command: ['sleep', '9999999999']
        command: ['python3']
        args: ['app.py', 'runserver', '--host', '0.0.0.0', '-d', '-r']
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: mysql_db_name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: mysql_user
        - name: MYSQL_USER_PASSWD
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: mysql_user_pw

  