apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: jamielsharief/mysql:latest
        name: mysql
        imagePullPolicy: Never
      
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: mysql_root_pw
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: mysql_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: mysql_user_pw
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: mysql_db_name
        volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim